# Generated by Django 4.0.6 on 2022-07-05 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(5000)])),
                ('img', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_best_selling', models.BooleanField(default=False)),
            ],
        ),
    ]
