# Generated by Django 4.0.6 on 2022-07-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_product_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
